/* MTI_DPI */

/*
 * Copyright 2002-2015 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win32pe'
 */
#ifndef INCLUDED_TBXBINDINGS
#define INCLUDED_TBXBINDINGS

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
close_tracefiles();

DPI_LINK_DECL DPI_DLLESPEC
int
init_temp_mem();

DPI_LINK_DECL DPI_DLLESPEC
int
init_tracefiles();

DPI_LINK_DECL DPI_DLLESPEC
int
send_word_to_hdl(
    svLogicVecVal* address,
    svLogicVecVal* data,
    svLogic* done);

DPI_LINK_DECL DPI_DLLESPEC
int
write_mem_trace(
    const svLogicVecVal* mem_type,
    const svLogicVecVal* trace_address,
    const svLogicVecVal* data_bus,
    const svLogicVecVal* data_mem);

#endif 
